### ISSUE TITLE
image for core database architecture

### ISSUE THREAD

**Issue by mdsie** [BONSAMURAIS/bonsai#1]
![wg-bonsai-2](https://cloud.githubusercontent.com/assets/25055429/24054362/362232cc-0b3c-11e7-95bb-f0ad206e6560.png)
![wg-bonsai-3](https://cloud.githubusercontent.com/assets/25055429/24054365/3828f074-0b3c-11e7-9222-31d109006f87.png)
![wg-bonsai-4](https://cloud.githubusercontent.com/assets/25055429/24054369/39fcedd8-0b3c-11e7-97b3-cb8e1643b3c0.png)

**Comment by mklarmann** [comment]
I could at it per drag&drop here: https://github.com/BONSAMURAIS/bonsai/wiki/Core-Database

maybe relocate it.

**Comment by mdsie** [comment]
Thanks, you are right it should be relocated. (I posted it here because it was the easiest way for me to get an URL I could refer to). But it is not a final graph it should also be reviewed and modified, so maybe too soon to add it yet?

**Comment by mklarmann** [comment]
then just delete it from the wiki again. <http://tedxtalks.ted.com/video/Eating-is-an-environmental-actM>
