### ISSUE TITLE
Complete the getting-started guide

### ISSUE THREAD

**Issue by tmillross** [BONSAMURAIS/bonsai#13]
Following discussion including @romainsacchi @cmutel and @MicDr, a _getting-started guide_ has been drafted on the Wiki [here](https://github.com/BONSAMURAIS/bonsai/wiki/Getting-started). 
Page edits and suggestions are welcome.
Requirements:
- [x]  Finish writing content
- [x]  Move to an appropriate location within the information hierarchy
- [x]  Link to the guide from relevant locations (website, organisation front page...?)

**Comment by tmillross** [comment]
I've added the content I think is most appropriate for now. Glad to receive additions, critical feedback etc.

**Comment by romainsacchi** [comment]
Should the tasks listed in the Hackathon agenda be tuned into Issues within the Hackathon's subrepo? @tmillross so that we do not mix them with the general high-level tasks?

**Comment by MicDr** [comment]
Agree, otherwise we re-duplicate content. An issue may rise if a general high-level task matches more or less with a task on the Hackathon agenda

**Comment by romainsacchi** [comment]
@MicDr  True that. But within an issue, one can reference to another issue in another repo I think. So one could say that this issue relates to another one in the Hackathon repo, or something like that.

**Comment by cmutel** [comment]
It might make sense to hold off on taking the agenda too seriously, as
it will change in response to what the working groups think is
possible before and during the hackathon. For the time being, I guess
we could put in some general tasks to give newcomers and idea of what
to expect, but it shouldn't be any more detailed than that.

On Wed, 13 Mar 2019 at 08:52, romainsacchi <notifications@github.com> wrote:
>
> @MicDr True that. But within an issue, one can reference to another issue in another repo I think. So one could say that this issue relates to another one in the Hackathon repo, or something like that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
############################
Chris Mutel
Technology Assessment Group, LEA
Paul Scherrer Institut
OHSA D22
5232 Villigen PSI
Switzerland
http://chris.mutel.org
Telefon: +41 56 310 5787
############################

**Comment by tngTUDOR** [comment]
> @MicDr True that. But within an issue, one can reference to another issue in another repo I think. So one could say that this issue relates to another one in the Hackathon repo, or something like that.

Cards in the project management can be turned into issues as well, so references to other issues at other repositories can also be done (after turning the card to an issue)

**Comment by tmillross** [comment]
The most recent plan is to move this getting-started content to the [Bonsai ](https://github.com/BONSAMURAIS/bonsai) repo [readme](https://github.com/BONSAMURAIS/bonsai/blob/master/README.md) as suggested in  [BEP0004](https://github.com/BONSAMURAIS/enhancements/blob/bep4-communications/beps/0004-bonsai-communication-strategy.md).

**Comment by tmillross** [comment]
> The most recent plan is to move this getting-started content to the Bonsai repo readme as suggested in BEP0004.

This move has now been completed and the text updated to current state.
