### ISSUE TITLE
Reorganize readme and 'pieces of code'

### ISSUE THREAD

**Issue by massimopizzol** [BONSAMURAIS/bonsai#16]
The first thing one reads when opening the bonsai repository is "pieces of code....". then there are some words about what bonsai is and the text about stepwise... seems quite messy. Or at least it doesn't seem a meaningful introduction to a repository that has the same name as the organisation and that contains several projects.

This Readme.md file could probably be updated with more meaningful information on what the repository really is about.

The "pieces of code" could at least be placed in a separate folder with appropriate name.

**Comment by romainsacchi** [comment]
I agree. The purpose of this repository should be clarified.
As I see it, it could be one of the following:

- a repo dedicated to documentation, description of the Bonsai philosophy and other information.

- a repo dedicated to host issues about the conception of the Bonsai software, where we could discuss for each task which tools to use, etc., and use the Project board within that repo (or use the Project board at the first level, filled with Issues from this repo).

- a repo dedicated to host pieces of code and data each of us think could be useful.

**Comment by massimopizzol** [comment]
I would also go for a generic repo dedicated to host issues about the development and application of the Bonsai software. Issues from this repo should then be used and organised in Project boards at the first level.

**Comment by tngTUDOR** [comment]
From my experience, issues are better organized if they belong to a
specific repository and not a full "project".
If I ever visit a repository, I think that seeing the issues is more
helpful to identify if a problem I am facing is already reported there or
not.

I suggest: One repository for a software module (python package for
example) with it's own issue and it's own "project".
The BONSAMURAIS organization can have one "project" where multiple
repositories are associated (and hence help to keep an overview of the
issues and work being done)

**Comment by romainsacchi** [comment]
@tngTUDOR  So, the module "text mining" would have its own repo, for example? With its own issues, milestones, etc.?

**Comment by tngTUDOR** [comment]
Yes, like bw2:
you have one umbrella repository, when installed, you pull packages that
are independant (bw2io, bw2calc, bw2data, etc.)


Pandas is one huge package, and it makes sense for such a package to have
only one repository for example, or openlca, where everything is in one
single application.

**Comment by romainsacchi** [comment]
Interesting. My opinion is that this question of repositories organization should be fixed ASAP before its gets even messier. Should we come up with 2-3 possibilities and proceed to a quick vote?
@cmutel @MicDr @tmillross @massimopizzol @tngTUDOR

**Comment by cmutel** [comment]
:+1: to separate repos instead of a monorepo. Each of our children will grow at different rates and find their own path in the world. They will each have their own team of "parents" as well.

I don't think we need to have "text mining" as an issue until there are specific proposals for projects that new members can work on. I have tried to identify some [more specific components](https://chris.mutel.org/bonsai-components.html) which might fit better.

Using a project board for [hackathon deliverables](https://github.com/orgs/BONSAMURAIS/projects/2) has clicked well for me, as this allows some overarching issues (e.g. a release) to be a card in the board, while other issues just stay issues.

**Comment by massimopizzol** [comment]
So bonsai should be a repo for XXX and should contain  issues that are specific for that repo only. Then in the first level we can create projects that contain one (or more) repositories. So the hierarchy is: Project board (contains) > repository (contains) > issues. 
Correct?

Fine for me, now the question remains what should the bonsai repo be used for and how to update the readme.

**Comment by tngTUDOR** [comment]
Here is the way I see it:


BONSAMURAI organization account of github will group several repositories:
one for a "database" for example, and one for the python package that will
be used to query the database to load data from it and do some
calculations, another one for the python package that allows to export the
results, and maybe in the future another one with a REST API that puts
everything in a single platform, and maybe later a repository with a web
application that is capable using the platform.


The way I see it, ideally, each deliverable of the hackaton could have it's
own repository.

**Comment by romainsacchi** [comment]
And by repository, we mean a unique domain (e.g., https://github.com/bonsai_rest_API)?

**Comment by MicDr** [comment]
The thing is that it is apparently not clear yet what this repo shoud be about now that we are duplicating them under Bonsamurais...

**Comment by massimopizzol** [comment]
What @tngTUDOR proposes is already happening as there are several repositories under the overall BONSAI account. Then how to organize them is also discussed [here](https://github.com/BONSAMURAIS/bonsai/issues/10). If I understand right one way of organising stuff **could** be for example to include/group repositories of the hackathon [like e.g. this one](https://github.com/BONSAMURAIS/hackathon-2019) within/under the [hackathon project board](https://github.com/orgs/BONSAMURAIS/projects/2). Correct?

This specific issue instead is about the [BONSAMURAIS/bonsai](https://github.com/BONSAMURAIS/bonsai) repository that right now is a mess. :)

**Comment by MicDr** [comment]
I tend to agree with your last message @massimopizzol even thought this structure has so far been spontaneous and it has not been formalized. 
referring to your first message, this is also the reason why the opening of the bonsai repository is still "pieces of code....": because it is not clear yet what that repo should contain. My opinion about it is in the [discussion list](https://bonsai.groups.io/g/main/topic/a_new_project_board_to/30414053?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,30414053)

**Comment by massimopizzol** [comment]
OK I see Michele has directly edited the README file so I am closing this issue as this specific discussion is not more relevant. I suggest also that:
- We might discuss the specific use of the bonsai repo by filing a specific issue.
- We keep discussing how to organize repositories [here](https://github.com/BONSAMURAIS/bonsai/issues/10).

**Comment by MicDr** [comment]
I think your point is still valid Massimo, and the purpose of this directory is still not clear; 
I rephrased some of the text and removed some of the content that was clearly outdated (e.g. that Exiobase license was not open source). I think it is a very good idea to move this discussion as you suggested. If the others agree we can close this issue

**Comment by massimopizzol** [comment]
No problem, fine for me. For me the specific issue is solved (we have 'reorganized readme and pieces of code') and should be closed. How to use this rep and what is should be for is a different topic and should be discussed in another issue made only for that IMO. Thanks for the valuable discussion so far.

**Comment by MicDr** [comment]
Ok :)  However, while we discuss the overall purpose of the bonsai directory, any contribution to further improve pieces and bits of the read me file is very welcome (so that who reads it in the meantime finds more coherent information).
